### ISSUE TITLE
exists? doesn't work with Ruby 3.3.1

### ISSUE THREAD

**Issue by laraferroni** [westonganger/capistrano-precompile-chooser#4]
It's possible this stopped working with an earlier version of ruby, but when we recently upgraded to Ruby 3.3.1, we ran into:

0.9.2/lib/capistrano/precompile_chooser/local_precompile.rake:37:in `block (6 levels) in eval_rakefile': undefined method `exists?' for class Dir (NoMethodError)
Did you mean?  exist?

I forked the gem for our use, but local_precompile.rake should be updated to:

commands << "#{fetch(:rsync_cmd)} #{remote_shell} ./#{fetch(:assets_dir)}/ #{server.user}@#{server.hostname}:#{release_path}/#{fetch(:assets_dir)}/" if Dir.exist?(fetch(:assets_dir))
            commands << "#{fetch(:rsync_cmd)} #{remote_shell} ./#{fetch(:packs_dir)}/ #{server.user}@#{server.hostname}:#{release_path}/#{fetch(:packs_dir)}/" if Dir.exist?(fetch(:packs_dir))

**Comment by westonganger** [comment]
Thanks for pointing that out, I will fix this. You definitely could have created a PR with those changes.

Its odd that the application that I am running this with did not exhibit this issue on all my Ruby upgrades up to and including Ruby 3.3.x

**Comment by westonganger** [comment]
v0.9.3 of this gem is now released which contains the fix for this.

**Comment by laraferroni** [comment]
Awesome. Thanks!
